### ISSUE TITLE
FYI, Licensing trash

### ISSUE THREAD

**Issue by artificialai223** [breftejk/Discord.js-Web-Dashboard#42]
This new "license" system makes the entire software not for helping users but for profit. I am here to request the licensing be removed as it is a obstacle for small developers looking to grow and when the package is obfuscated you could include anything to maliciously attack the user's bots.

**Comment by artificialai223** [comment]
I will be using the previous version before the licensing as I disagree with this approach.

**Comment by PlainDevelopment** [comment]
The only obfuscated file is index.js, I can confirm this file includes nothing malicious as it checks for the license and then references other files (which are unobfuscated; you can take a look).
We also require profit to keep Assistants stable, paying for VPS, domains and other stuff is not cheap.

**Comment by PlainDevelopment** [comment]
Yet you can still use the module with the 'opensource' license, it's completely free.
For more information about licenses, check out [this site](https://licenses.assistants.ga/).

**Comment by breftejk** [comment]
Hello!

Thank you for your feedback. We understand that you may have doubts about the performance of Dashboard by obfuscating it - but just use simple deobfuscator, you will see more or less what the source code contains. We do not and do not intend to put malicious code there. We just want to make it harder to bypass the license system, which will stay with us.
In addition, the index.js file does not contain anything that is relevant and usable when editing the code for your own desires and additions. Everything else you need (routes, moduleExportsFunctions, etc.) can be found in separate, non-obfuscated, editable files.

We understand your dissatisfaction, however, the license system was created in order to - as you say - make a minimal profit from the project. It's not a big price to pay, and maintaining the project also costs us some money.

We are constantly introducing updates to improve the user experience of the Dashboard, however, this is also on par with using the latest versions of the Dashboard - they contain more features, are designed to improve and enhance the user experience and the safety of the bot and those using the Dashboard. Available Theme due to the technological advancement of the project will also stop supporting Dashboard in previous versions over time, which defeats the purpose.

A paid license was created only to make money from something someone else is making money from. We do not make it difficult for users to use the project for free, unless they draw financial benefits from it.

Thank you for your feedback and please be assured that we never meant to make it difficult for individuals to use the project - that's what it was created for, and that's why it exists!

_Best regards,_
_breftejk - Project Developer and Assistants Center CEO_

**Comment by artificialai223** [comment]
> The only obfuscated file is index.js, I can confirm this file includes nothing malicious as it checks for the license and then references other files (which are unobfuscated; you can take a look). We also require profit to keep Assistants stable, paying for VPS, domains and other stuff is not cheap.

Domains etc are not required for a dashboard package, The developer using the package pays forthose and what is to say that nothing is malicious? Arenwe supposed to just "take your word for it"?

**Comment by PlainDevelopment** [comment]
This issue has been closed, if you wish to discuss more; please contact breathtake directly on [discord](https://discord.gg/DRxfU8wtu8).

**Comment by DeveloperNeon** [comment]
I get you need money to support the project, but you could try other ways.

**Comment by breftejk** [comment]
Yes. And we do. In v3.
